// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOiAXv3aLAzegOqgDYeFAiF1bWtmsFaNs',
    appId: '1:788375089101:android:0f3a16631a9583920e1e84',
    messagingSenderId: '788375089101',
    projectId: 'flutter-prep-a53fc',
    databaseURL: 'https://flutter-prep-a53fc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-prep-a53fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA0k_9Ev8HkpB_fB9B-EwVdM_bQRaYDmA',
    appId: '1:788375089101:ios:a94705ddcb7411760e1e84',
    messagingSenderId: '788375089101',
    projectId: 'flutter-prep-a53fc',
    databaseURL: 'https://flutter-prep-a53fc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-prep-a53fc.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
